services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port for AMQP
      - "15672:15672" # RabbitMQ management console
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    #    command: >
    #      sh -c "rabbitmq-plugins enable rabbitmq_web_stomp &&
    #             rabbitmq-plugins enable rabbitmq_stomp &&
    #             rabbitmq-plugins enable rabbitmq_management &&
    #             rabbitmq-server"
    networks:
      - ws-network

  app:
    build:
      context: .
    ports:
      - "8080:8080" # Maps the application's port
    depends_on:
      - rabbitmq # Ensures RabbitMQ starts before the app
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - ws-network

networks:
  ws-network:
    driver: bridge